const basicRouter = {
    route: null,
    name: null,
    title: '基础数据',
    type: 'folder', // 类型: folder, tab, view
    icon: 'iconfont icon-tushuguanli',
    filePath: 'views/book/', // 文件路径
    order: null,
    inNav: true,
    children: [
      {
        title: '物料数据',
        type: 'folder',
        name: 'bookAdd',
        route: '/book/add',
        filePath: 'views/book/BookAdd.vue',
        inNav: true,
        icon: 'iconfont icon-tushuguanli',
        children: [
            {
              title: '五金材料',
              type: 'view',
              name: 'userList',
              route: '/admin/user/list',
              filePath: 'views/admin/user/UserList.vue',
              inNav: true,
              icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '木材数据',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '板材数据',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '特殊材料',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '刀具数据',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '油漆数据',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            },
        ],
      },
      {
        title: 'Topsolid数据',
        type: 'folder',
        name: 'bookAdd',
        route: '/book/list',
        filePath: 'views/book/BookList.vue',
        inNav: true,
        icon: 'iconfont icon-tushuguanli',
        children: [
            {
              title: '开料流程',
              type: 'view',
              name: 'userList',
              route: '/admin/user/list',
              filePath: 'views/admin/user/UserList.vue',
              inNav: true,
              icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '五金属性',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '程序类型',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '封边信息',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            }
        ],
      },
      {
        title: '其他数据',
        type: 'folder',
        name: 'bookAdd',
        route: '/book/list',
        filePath: 'views/book/BookList.vue',
        inNav: true,
        icon: 'iconfont icon-tushuguanli',
        children: [
            {
              title: '设备数据',
              type: 'view',
              name: 'userList',
              route: '/admin/user/list',
              filePath: 'views/admin/user/UserList.vue',
              inNav: true,
              icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '产品数据',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            },
            {
                title: '报价模板',
                type: 'view',
                name: 'userList',
                route: '/admin/user/list',
                filePath: 'views/admin/user/UserList.vue',
                inNav: true,
                icon: 'iconfont icon-huiyuanguanli',
            }
        ],
      },
    ],
  }
  
  export default basicRouter
  