const pdmRouter = {
    route: null,
    name: null,
    title: 'PDM管理',
    type: 'folder',
    icon: 'iconfont icon-huiyuanguanli',
    filePath: 'views/pdm/',
    order: null,
    inNav: true,
    children: [
      {
        route: '/pdm',
        name: null,
        title: '设计管理',
        type: 'folder', // 取 route 为默认加载页
        icon: 'iconfont icon-huiyuanguanli',
        filePath: 'views/admin/user/',
        inNav: true,
        children: [
          {
            title: '设计需求',
            type: 'view',
            name: 'userList',
            route: '/admin/user/list',
            filePath: 'views/admin/user/UserList.vue',
            inNav: true,
            icon: 'iconfont icon-huiyuanguanli',
          },
          {
            title: '任务分配',
            type: 'view',
            name: 'userList',
            route: '/admin/user/list',
            filePath: 'views/admin/user/UserList.vue',
            inNav: true,
            icon: 'iconfont icon-huiyuanguanli',
          },
          {
            title: '设计绩效',
            type: 'view',
            name: 'userList',
            route: '/admin/user/list',
            filePath: 'views/admin/user/UserList.vue',
            inNav: true,
            icon: 'iconfont icon-huiyuanguanli',
          },
        ],
      },
      {
        route: '/worksheet',
        name: null,
        title: '设计数据',
        type: 'folder', // 取 route 为默认加载页
        icon: null,
        filePath: 'views/admin/group',
        inNav: true,
        children: [
          {
            route: '/admin/group/list',
            type: 'view',
            name: 'groupList',
            inNav: true,
            filePath: 'views/admin/group/GroupList.vue',
            title: '数据管理',
            icon: 'iconfont icon-huiyuanguanli',
          },
          {
            route: '/admin/group/add',
            type: 'view',
            name: 'groupAdd',
            filePath: 'views/admin/group/GroupAdd.vue',
            inNav: true,
            title: '材料赋值',
            icon: 'iconfont icon-add',
          },
          {
            route: '/admin/group/add',
            type: 'view',
            name: 'groupAdd',
            filePath: 'views/admin/group/GroupAdd.vue',
            inNav: true,
            title: '标准产品入库',
            icon: 'iconfont icon-add',
          },
          {
            route: '/admin/group/add',
            type: 'view',
            name: 'groupAdd',
            filePath: 'views/admin/group/GroupAdd.vue',
            inNav: true,
            title: '模型管理',
            icon: 'iconfont icon-add',
          },
        ],
      },
      {
        route: '/worksheet',
        name: null,
        title: '设计规范',
        type: 'folder', // 取 route 为默认加载页
        icon: null,
        filePath: 'views/admin/group',
        inNav: true,
        children: [
          {
            route: '/admin/group/list',
            type: 'view',
            name: 'groupList',
            inNav: true,
            filePath: 'views/admin/group/GroupList.vue',
            title: '问题反馈',
            icon: 'iconfont icon-huiyuanguanli',
          },
          {
            route: '/admin/group/add',
            type: 'view',
            name: 'groupAdd',
            filePath: 'views/admin/group/GroupAdd.vue',
            inNav: true,
            title: '设计规范',
            icon: 'iconfont icon-add',
          },
          {
            route: '/admin/group/add',
            type: 'view',
            name: 'groupAdd',
            filePath: 'views/admin/group/GroupAdd.vue',
            inNav: true,
            title: '规范报表',
            icon: 'iconfont icon-add',
          },
        ],
      },
    ],
  }
  
  export default pdmRouter
  